/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indizador.java
 *
 * Created on 22-jul-2010, 5:15:34
 */

package Gestores;

import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author Yaka
 */
public class Indizador extends javax.swing.JFrame {

    /** Creates new form Indizador */
    public Indizador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAcciones = new javax.swing.JTextArea();
        btnIndexar = new javax.swing.JButton();
        btnExaminar = new javax.swing.JButton();
        jtRuta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WayraSearch Indexer");

        jtaAcciones.setColumns(20);
        jtaAcciones.setEditable(false);
        jtaAcciones.setRows(5);
        jScrollPane1.setViewportView(jtaAcciones);

        btnIndexar.setText("Indexar");
        btnIndexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndexarindexarArchivo(evt);
            }
        });

        btnExaminar.setText("Examinar");
        btnExaminar.setToolTipText("Seleccione el archivo que desea indexar o reindexar.");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarbuscarArchivo(evt);
            }
        });

        jtRuta.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnExaminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnIndexar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExaminar)
                    .addComponent(jtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIndexar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIndexarindexarArchivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndexarindexarArchivo
        File DirectorioInicial = new File(jtRuta.getText());//"D:\\Facu\\2009\\DLC\\DLC-Final-2010\\test");

        if (DirectorioInicial.isDirectory()) {
            Date dateobj = new Date();
            long startTime = dateobj.getTime();
            System.out.println("Indización iniciada: " + startTime);

            GestorDirectorio.indizar(DirectorioInicial);

            Date dateobj2 = new Date();
            long endTime = dateobj2.getTime();
            jtaAcciones.append("Inidzacion finalizada: " + endTime);
            jtaAcciones.append("Duracion: " + ((endTime-startTime)/1000) );

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un directorio.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnIndexarindexarArchivo

    private void btnExaminarbuscarArchivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarbuscarArchivo
        JFileChooser j=new JFileChooser();
        j.setFileSelectionMode(j.DIRECTORIES_ONLY);
        int n=j.showOpenDialog(null);
        File f = j.getSelectedFile();
        jtRuta.setText(f.getAbsolutePath());
    }//GEN-LAST:event_btnExaminarbuscarArchivo

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Indizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnIndexar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtRuta;
    private javax.swing.JTextArea jtaAcciones;
    // End of variables declaration//GEN-END:variables

}
